name: Build Content

on:
  push:
    branches:
      - sphinx-build
      - pre-build
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: sphinx-build
      - name: Check out sphinx-build
        run: |
          git config --global user.name 'Github-Robot'
          git config --global user.email 'github-robot@users.noreply.github.com'
      - name: Clone Content repositories
        run: |
          git clone --depth=1 -b "pre-build" https://github.com/input-output-hk/technical-docs.git source
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/cardano-wallet.git git/cardano-wallet
          mkdir source/cardano-wallet
          cp -r git/cardano-wallet/doc source/cardano-wallet
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/cardano-rest.git git/cardano-rest
          mkdir source/cardano-rest
          cp -r git/cardano-rest/doc source/cardano-rest
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/cardano-node.git git/cardano-node
          mkdir source/cardano-node
          cp -r git/cardano-node/doc source/cardano-node
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/cardano-ledger-specs.git git/cardano-ledger-specs
          mkdir source/cardano-ledger-specs
          cp -r git/cardano-ledger-specs/doc source/cardano-ledger-specs
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/cardano-tutorials.git git/cardano-tutorials
          mkdir source/cardano-tutorials
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/plutus.git git/plutus
          mkdir source/plutus
          cp -r git/plutus/doc source/plutus
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/adrestia.git git/adrestia
          mkdir source/adrestia
          cp -r git/adrestia/doc source/adrestia
          echo "Success"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -U sphinx
          export PATH=$PATH:/home/runner/.local/bin
          make html
      - name: Clone Destination
        run: |
          cd ../
          git clone -b "main" https://github.com/input-output-hk/technical-docs.git dest
          git rm -r dest/*
          cp -r technical-docs/build/* dest
          cd dest
          git add .
          git commit -am "Update"
          git push