name: Build Content

on:
  push:
    branches:
      - sphinx-build
      - pre-build
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: sphinx-build
      - name: Check out sphinx-build
        run: |
          git config --global user.name 'Github-Robot'
          git config --global user.email 'github-robot@users.noreply.github.com'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Clone Content repositories
        run: |
          git clone --depth=1 -b "pre-build" https://github.com/input-output-hk/technical-docs.git source
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/cardano-wallet.git source/cardano-wallet
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/cardano-rest.git source/cardano-rest
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/cardano-node.git source/cardano-node
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/cardano-ledger-specs.git source/cardano-ledger-specs
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/cardano-tutorials.git source/cardano-tutorials
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/plutusgit source/plutus
          git clone --depth=1 -b "robcohen/docs" https://github.com/input-output-hk/adrestia.git source/adrestia
      - name: Build Sphinx
        run: |
          make html
      - name: Clone Destination
        run: |
          echo "THIS DIR"
          echo $(pwd)
          cd ../
          git clone -b "main" https://github.com/input-output-hk/technical-docs.git dest