---
name: Build Content

on:
  push:
    branches:
      - sphinx-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `sphinx-build` branch
        uses: actions/checkout@v2
        with:
          ref: sphinx-build
          path: sphinx-build
      - name: Checkout `main` branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - run: |
          cd sphinx-build
          git config --global user.name 'Github-Robot'
          git config --global user.email 'github-robot@users.noreply.github.com'
          export PATH=$PATH:/home/runner/.local/bin
      - name: Clone Content repositories
        run: |
          cd sphinx-build
          git clone --depth=1 -b "robcohen/docs" \
          https://github.com/input-output-hk/cardano-tutorials.git \
          source/cardano-tutorials
          rm -rf source/cardano-tutorials/.git
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3
      - name: Install dependencies
        run: |
          cd sphinx-build
          export PATH=$PATH:/home/runner/.local/bin
          pip3 install -r requirements.txt
          make html
      - name: Clear main branch
        run: |
          cd main
          git rm -rf *
          cp -r ../sphinx-build/source/* ./
          git add .
          git commit -am "Update"
          git push
